---
ansible_connection: local
ubuntu_target_version_name: jammy
ubuntu_target_version: 22.04
jetbrains_mono_version: 1.0.3
git_email: donald.duck@ducktown.com
git_user: Donald Duck
system_autoproxy_url: http://localhost:3130/proxy.pac
