---
# Go language SDK version number
golang_version: '1.25.5'

golang_architecture: amd64

golang_redis_filename: 'go{{ golang_version }}.linux-{{ golang_architecture }}.tar.gz'

# Mirror to download the Go language SDK redistributable package from
golang_mirror: 'https://go.dev/dl'

# Base installation directory the Go language SDK distribution
golang_install_dir: '/opt/go/{{ golang_version }}'

# Directory to store files downloaded for Go language SDK installation
golang_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"

# Location for GOPATH environment variable
golang_gopath:

golang_redis_sha256sum: 'adab2483f644e2f8a10ae93122f0018cef525ca48d0b8764dae87cb5f4fd4206'
